[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "livekit"
authors = [{name = "Theo Monnom", email = "theo.monnom@outlook.com"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: Apache Software License"]
dynamic = ["version", "description"]

[project.urls]
"Homepage" = "https://github.com/livekit/client-sdk-python"